---
title: "MiniProject2_WebScraping"
author: "Cynthia Budiyanto and Willemijn Leiner"
format: pdf
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(rvest)
library(tidyverse)
library(stringr)
library(polite)
library(htmltools)
library(purrr)
```

```{r}
#| eval: false
# Defining the url to be its own value to make it easier to work with
url <- "https://link.springer.com/search?facet-journal-id=12968&query=machine+learning&content-type=Article&dateFrom=&dateTo=&sortBy=relevance"

# Parse the HTML content of the page
page <- read_html(url)

# Extracting article titles using the CSS selector
titles <- page |>
  html_elements("a.app-card-open__link") |>
  html_text()

titles

# Extracting relative URLs for each article
links <- page |>
  html_elements("a.app-card-open__link") |>
  html_attr("href")
links <- paste0("https://link.springer.com", links)

# Extracting publication date 
dates <- page |>
  html_elements(".app-card-open__meta") |>
  html_text()

# Cleaning the date strings
dates_clean <- dates |>
  str_squish()
dates_clean <- dates_clean |>
  str_remove("Open access")
dates_clean <- dates_clean |>
  str_squish()
dates_clean

# Combining the extracted data into a single tibble for inspection
articles <- tibble(
  title = titles,
  date  = dates_clean,
  link  = links
)

view(articles)
```

## FUNCTION 1: SCRAPING INDIVIDUAL ARTICLE LINKS

```{r}
#| eval: false
get_link_from_search <- function(page, css_code) {                      # defining the function "get_link_from_search", with two arguments
  link <- page |>                                                       # piping the object "page" into the next function
    html_elements(css_code) |>                                          # find all html elements that match the CSS code
    html_attr("href")                                                   # extracts the value of the "href" attribute from each selected element.
}

scrape_list_links1 <- function(url) {                                   # defining the function "scrape_list_links1" that will take our url
  Sys.sleep(3)                                                          # polite scraping
  session <- bow(url, force = TRUE)                                     # creates a browser session for the given URL
  page <- scrape(session)                                               # scrape the given URL
  list_links <- get_link_from_search(page, ".app-card-open__link")      # extract the links using previous function that correspond to this CSS code
  complete_link <- paste0("https://link.springer.com", list_links)      # stitching the extracted links with base domain
  list(complete_link)                                                   # wraps it into a list of vector links :)
}
```

## FUNCTION 2: USING LINKS TO GET INDIVIDUAL ARTICLE INFO

```{r}
#| eval: false
get_info_from_page <- function(page, css_code) {                        # defining the function "get_info_from_search", with two arguments
  result <- page |>                                                     # piping the object "page" into the next function, saving the result into "result"
    html_elements(css_code) |>                                          # find all of the html elements that match the CSS code
    html_text(trim = TRUE)                                              # retrieve text content from each selected element. the argument trim = TRUE will trim leading and trailing spaces. 
  if (length(result) == 0)                                              # if length of the supposedly text string is 0 
    return(NA_character_)                                               # then return the value to be NA
  result[1]                                                             # take the first match only
}

scrape_individual_article <- function(x) {                              # defining the function "scrape_individual_article", with one argument "x"
  Sys.sleep(3)                                                          # polite scraping
  session <- bow(x, force = TRUE)                                       # creates a browser session for the URL(s) that we will supply from our list of url links
  page <- scrape(session)                                               # scrape the given URL
  jcmr_title <- get_info_from_page(page,                                # scrape the "title" element from each URL
                                   ".c-article-title")
  jcmr_vol <- get_info_from_page(page,                                  # scrape the "volume" element from each URL
                            ".c-article-identifiers--cite-list .c-article-identifiers__item:nth-child(1)")
  jcmr_abstract <- get_info_from_page(page,                             # scrape the "abstract" element from each URL
                                      "#Abs1-content p:nth-child(2)")
  jcmr_method <- get_info_from_page(page,                               # scrape the "method" element from each URL 
                                    "#Abs1-content p:nth-child(4)")
  jcmr_author <- get_info_from_page(page,                               # scrape the "authors" element from each URL
                                    "#main-content header")
  jcmr_type <- get_info_from_page(page,                                 # scrape the "article type" element from each URL
                                  ".c-article-title+ .c-article-identifiers .c-article-identifiers__item:nth-child(1)")
  jcmr_date <- get_info_from_page(page,                                 # scrape the "publishing date" element from each URL
                                  ".c-article-identifiers__item time")
  tibble(date = jcmr_date,                                              # create a tibble containing all of the scraped elements will modified column names
         title = jcmr_title, 
         volume = jcmr_vol, 
         authors = jcmr_author, 
         type = jcmr_type, 
         abstract = jcmr_abstract, 
         method = jcmr_method)
}
```

#### KEYWORD 1: "Machine Learning" 3 PAGES OF WEBSITE

```{r}
#| eval: false
# Scraping links from PAGE 1 - MACHINE LEARNING
pg1_ml <- scrape_list_links1("https://link.springer.com/search?query=machine+learning&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=1")

# Scraping links from PAGE 2 - MACHINE LEARNING
pg2_ml <- scrape_list_links1("https://link.springer.com/search?query=machine+learning&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=2")

# Scraping links from PAGE 3 - MACHINE LEARNING
pg3_ml <- scrape_list_links1("https://link.springer.com/search?query=machine+learning&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=3")

# Combining two pages into one list of links (55 links total)
ml <- list(pg1_ml, pg2_ml, pg3_ml)
clean_ml <- unlist(ml)

# Scraping information from each individual article
details_kw1 <- purrr::map(clean_ml, scrape_individual_article)        # Using our pre-made function "scrape_individual_particle" to be iterated for all of the vectors in the list
bind_rows(details_kw1)

# Turning the binded rows into a tibble
details_kw1 <- bind_rows(details_kw1)
```

#### KEYWORD 2: "Deep Learning" 3 PAGES OF WEBSITE

```{r}
#| eval: false
# Scraping links from PAGE 1 - DEEP LEARNING
pg1_dl <- scrape_list_links1("https://link.springer.com/search?query=deep+learning&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=1")

# Scraping links from PAGE 2 - DEEP LEARNING
pg2_dl <- scrape_list_links1("https://link.springer.com/search?query=deep+learning&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=2")

# Scraping links from PAGE 3 - DEEP LEARNING
pg3_dl <- scrape_list_links1("https://link.springer.com/search?query=deep+learning&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=3")

# Combining two pages into one list of links (54 links total)
dl <- list(pg1_dl, pg2_dl, pg3_dl)
clean_dl <- unlist(dl)

# Scraping information from each individual article
details_kw2 <- purrr::map(clean_dl, scrape_individual_article)        # Using our pre-made function "scrape_individual_particle" to be iterated for all of the vectors in the list 
bind_rows(details_kw2)

# Turning the binded rows into a tibble
details_kw2 <- bind_rows(details_kw2)
```

#### KEYWORD 3: "Convolution" 2 PAGES OF WEBSITE

```{r}
#| eval: false
# Scraping links from PAGE 1 - CONVOLUTION
pg1_con <- scrape_list_links1("https://link.springer.com/search?query=convolution&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=1")

# Scraping links from PAGE 2 - CONVOLUTION
pg2_con <- scrape_list_links1("https://link.springer.com/search?query=convolution&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=2")

# Combining two pages into one list of links (39 links total)
con <- list(pg1_con, pg2_con)
clean_con <- unlist(con)

# Scraping information from each individual article
details_kw3 <- purrr::map(clean_con, scrape_individual_article)       # Using our pre-made function "scrape_individual_particle" to be iterated for all of the vectors in the list
bind_rows(details_kw3)

# Turning the binded rows into a tibble
details_kw3 <- bind_rows(details_kw3)
```

#### KEYWORD 4: "Artificial Intelligence" 2 PAGES OF WEBSITE

```{r}
#| eval: false
# Scraping links from PAGE 1 - ARTIFICIAL INTELLIGENCE
pg1_ai <- scrape_list_links1("https://link.springer.com/search?query=artificial+intelligence&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=1")

# Scraping links from PAGE 2 - ARTIFICIAL INTELLIGENCE
pg2_ai <- scrape_list_links1("https://link.springer.com/search?query=artificial+intelligence&content-type=Article&sortBy=relevance&search-within=Journal&facet-journal-id=12968&page=2")

# Combining two pages into one list of links (38 links total)
ai <- list(pg1_ai, pg2_ai)
clean_ai <- unlist(ai)

# Scraping information from each individual article.
details_kw5 <- purrr::map(clean_ai, scrape_individual_article)        # Using our pre-made function "scrape_individual_particle" to be iterated for all of the vectors in the list
bind_rows(details_kw5)

# Turning the binded rows into a tibble
details_kw5 <- bind_rows(details_kw5)
```

```{r}
#| eval: false
# Combining all data tables with different key words into one tibble
all_articles <- bind_rows(
  details_kw1 |> 
    mutate(keyword = "machine learning"),
  details_kw2 |>
    mutate(keyword = "deep learning"),
  details_kw3 |> 
    mutate(keyword = "convolution"), 
  details_kw5 |> 
    mutate(keyword = "artificial intelligence")
)

# Creating the CSV file
write_csv(all_articles, "springer_articles.csv")
```
