---
title: "textanalysis_codes"
format: html
---

```{r}
#| echo: false
#| message: false

library(tidyverse)
library(ggplot2)
library(leaflet)
library(patchwork)
library(dplyr)
library(stringr)
library(lubridate)
library(tidytext)
library(textdata)
library(igraph)
library(ggraph)

jcmr <- read_csv("~/project-2/clean_jcmr.csv")
```

```{r}
#| include: false
# Adding specific stopwords. Here, we insert the "general" words, that we can  expect from any scientific article about CMR and fluff words that we would expect from any science journals (study, analysis, treatment, human, mechanisms, mode, findings, function, etc).

cmr_stopword <- c("study", "scientific", "high", "study", "increased", "induced", "levels", "expression", "potential", "treatment", "related", "significantly", "accumulation", "showed", "related", "specific", "yrs", "age", "effect", "effects", "results", "analysis", "revealed", "human", "1", "2", "3", "group", "formation", "reduced", "function", "decreased", "model", "fat", "compared", "based", "size", "size", "stability", "assessment", "method", "clinical", "activity", "findings", "mechanisms", "energy", "exposure", "content", "properties", "development", "higher", "metabolic", "disease", "red", "white", "recovery", "cellular", "additional", "simultaneously", "emulsion", "molecular", "identified", "compounds", "composition", "mature", "site", "extracts", "significant", "including", "light", "liquid", "wide", "range", "time", "mg", "kg", "dependent", "independent", "patients", "background", "objectives", "recent", "studies")

lexicon <-  rep("custom", times = length(word))

# Create a dataframe from the two vectors above
full_stopwords <- data.frame(cmr_stopword, lexicon)
names(full_stopwords) <- c("word", "lexicon")

# Add the dataframe to stop_words df that exists in the library stopwords
stop_words_fix <-  dplyr::bind_rows(stop_words, full_stopwords)
view(stop_words_fix)
```

```{r}
# Finding most frequent (individual) words based on abstract
# Please update stop word list accordingly

clean_jcmr |>
  select(abstract) |>
  mutate(abstract = str_to_lower(abstract)) |>
  unnest_tokens(output = word, input = abstract) |>
  anti_join(stop_words_fix) |>
  count(word, sort = TRUE) |>
  filter(word != "NA") |>
  slice_max(n, n = 20) |>
  ggplot(aes(fct_reorder(word, n), n)) +
  geom_col() +
  coord_flip()

abstract_bigram <- clean_jcmr |>
  unnest_tokens(bigram, abstract, token = "ngrams", n = 2) |>
  filter(bigram != "NA") |>
  filter(!str_detect(bigram, "^\\d")) |>
  count(bigram, sort = TRUE) |>
  separate(bigram, c("word1", "word2"), sep = " ") |>
  filter(!word1 %in% stop_words_fix$word,
         !word2 %in% stop_words_fix$word) |>
  filter(!is.na(word1) & !is.na(word2)) |>
  unite(bigram, word1, word2, sep = " ")

abstract_trigram <- clean_jcmr |>
  unnest_tokens(bigram, abstract, token = "ngrams", n = 3) |>
  filter(bigram != "NA") |>
  filter(!str_detect(bigram, "^\\d")) |>
  count(bigram, sort = TRUE) |>
  separate(bigram, c("word1", "word2", "word3"), sep = " ") |>
  filter(!word1 %in% stop_words_fix$word,
         !word2 %in% stop_words_fix$word,
         !word3 %in% stop_words_fix$word) |>
  filter(!is.na(word1) & !is.na(word2) & !is.na(word3)) |>
  unite(bigram, word1, word2, word3, sep = " ")
```


```{r}
# Finding most frequent (individual) words based on title
# Please update stop word list accordingly

clean_jcmr |>
  select(title) |>
  mutate(title = str_to_lower(title)) |>
  unnest_tokens(output = word, input = title) |>
  anti_join(stop_words_fix) |>
  count(word, sort = TRUE) |>
  filter(word != "NA") |>
  slice_max(n, n = 20) |>
  ggplot(aes(fct_reorder(word, n), n)) +
  geom_col() +
  coord_flip()

title_bigram <- clean_jcmr |>
  unnest_tokens(bigram, title, token = "ngrams", n = 2) |>
  filter(bigram != "NA") |>
  filter(!str_detect(bigram, "^\\d")) |>
  count(bigram, sort = TRUE) |>
  separate(bigram, c("word1", "word2"), sep = " ") |>
  filter(!word1 %in% stop_words_fix$word,
         !word2 %in% stop_words_fix$word) |>
  filter(!is.na(word1) & !is.na(word2)) |>
  unite(bigram, word1, word2, sep = " ")

title_trigram <- clean_jcmr |>
  unnest_tokens(bigram, title, token = "ngrams", n = 3) |>
  filter(bigram != "NA") |>
  filter(!str_detect(bigram, "^\\d")) |>
  count(bigram, sort = TRUE) |>
  separate(bigram, c("word1", "word2", "word3"), sep = " ") |>
  filter(!word1 %in% stop_words_fix$word,
         !word2 %in% stop_words_fix$word,
         !word3 %in% stop_words_fix$word) |>
  filter(!is.na(word1) & !is.na(word2) & !is.na(word3)) |>
  unite(bigram, word1, word2, word3, sep = " ")
```


```{r}
# Finding most frequent (individual) words based on method
# Please update stop word list accordingly

clean_jcmr |>
  select(method) |>
  mutate(method = str_to_lower(method)) |>
    mutate(method = str_replace_all(
      method,
      "cardiovascular magnetic resonance",
      "cmr"
    )
  ) |>
  mutate(method = str_replace_all(
      method,
      "magnetic resonance imaging",
      "mri"
    )
  ) |>
    mutate(method = str_replace_all(
      method,
      "dice similarity coefficient",
      "dsc"
    )
  ) |>
  mutate(method = str_replace_all(
      method,
      "late gadolinium enhancement",
      "lge"
    )
  ) |>
    mutate(method = str_replace_all(
      method,
      "magnetic resonance angiography",
      "mra"
    )
  ) |>
  unnest_tokens(output = word, input = method) |>
  anti_join(stop_words_fix) |>
  count(word, sort = TRUE) |>
  filter(word != "NA") |>
  slice_max(n, n = 20) |>
  ggplot(aes(fct_reorder(word, n), n)) +
  geom_col() +
  coord_flip()

method_bigram <- clean_jcmr |>
  unnest_tokens(bigram, method, token = "ngrams", n = 2) |>
  filter(bigram != "NA") |>
  filter(!str_detect(bigram, "^\\d")) |>
  count(bigram, sort = TRUE) |>
  separate(bigram, c("word1", "word2"), sep = " ") |>
  filter(!word1 %in% stop_words_fix$word,
         !word2 %in% stop_words_fix$word) |>
  filter(!is.na(word1) & !is.na(word2)) |>
  unite(bigram, word1, word2, sep = " ")

method_trigram <- clean_jcmr |>
  select(method) |>
  mutate(method = str_to_lower(method)) |>
  mutate(method = str_replace_all(
      method,
      "cardiovascular magnetic resonance",
      "cmr"
    )
  ) |>
  mutate(method = str_replace_all(
      method,
      "magnetic resonance imaging",
      "mri"
    )
  ) |>
  unnest_tokens(bigram, method, token = "ngrams", n = 3) |>
  filter(bigram != "NA") |>
  filter(!str_detect(bigram, "^\\d")) |>
  count(bigram, sort = TRUE) |>
  separate(bigram, c("word1", "word2", "word3"), sep = " ") |>
  filter(!word1 %in% stop_words_fix$word,
         !word2 %in% stop_words_fix$word,
         !word3 %in% stop_words_fix$word) |>
  filter(!is.na(word1) & !is.na(word2) & !is.na(word3)) |>
  unite(bigram, word1, word2, word3, sep = " ")

```

